<a href="https://colab.research.google.com/github/abdalkarimnourddine/python-tutorial/blob/master/numpys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#import

In [0]:
import numpy as np

#Arrays

In [4]:
# Create a rank 1 array
a = np.array([0, 1, 2]) 
print (type(a))


<class 'numpy.ndarray'>


In [5]:
# this will print (the dimension of the array
print (a.shape) 
print (a[0])
print (a[1])
print (a[2])

(3,)
0
1
2


In [6]:
# Change an element of the array
a[0] = 5                 
print (a)                  

[5 1 2]


In [7]:
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])  
print (b.shape)                     
print (b)
print (b[0, 0], b[0, 1], b[1, 0])   

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


#Creating NumPy array

In [8]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3)) 
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Create a 2x2 array of all ones
b = np.ones((2,2))  
print (b)

[[1. 1.]
 [1. 1.]]


In [10]:
# Create a 3x3 constant array
c = np.full((3,3), 7) 
print (c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [11]:
# Create a 3x3 array filled with random values
d = np.random.random((3,3)) 
print (d)

[[0.31320201 0.56040803 0.2815425 ]
 [0.29332244 0.44419841 0.2007029 ]
 [0.30810796 0.07578347 0.38477791]]


In [12]:
# Create a 3x3 identity matrix
e = np.eye(3)        
print (e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# convert list to array
f = np.array([2, 3, 1, 0]) 
print (f)

[2 3 1 0]


In [14]:
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print (g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
# note mix of tuple and lists 
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])                           
print (h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [16]:
# create an array of range with float data type 
i = np.arange(1, 8, dtype=np.float)
print (i)

[1. 2. 3. 4. 5. 6. 7.]


In [17]:
# linspace() will create arrays with a specified number of items which are 
# spaced equally between the specified beginning and end values
j = np.linspace(2., 4., 3)
print (j)

[2. 3. 4.]


In [18]:
# indices() will create a set of arrays stacked as a one-higher 
# dimensioned array, one per dimension with each representing variation 
# in that dimension
k = np.indices((3,3))
print (k)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


#Datatypes

In [19]:
# Let numpy choose the datatype
x = np.array([0, 1])  
y = np.array([2.0, 3.0])  

# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)  

print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


#Array Indexing

Field Access

In [21]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print ("x['a'].shape: ",x['a'].shape)
print ("x['a'].dtype: ", x['a'].dtype)

print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)
print ("x['b'].dtype: ", x['b'])



x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64
x['b'].dtype:  [[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


slicing

In [25]:
x = np.array([5, 6, 7, 8, 9])
x[1:23:3]

array([6, 9])

In [26]:
print (x[-2:5])
print (x[-1:1:-1])

[8 9]
[9 8 7]


In [27]:
print(x)
x[4:]

[5 6 7 8 9]


array([9])

In [28]:
y = np.array([[[0],[1],[2],[3]], [[4],[5],[6]],[7]])
print ("Shape of y: ", y.shape)
y[1:3]

Shape of y:  (3,)


array([list([[4], [5], [6]]), list([7])], dtype=object)

In [29]:
x[...,0]

array(5)

In [30]:
# Create a rank 2 array with shape (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print ("Array a: ", a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print ("Array b: ", b)

Array a:  [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
Array b:  [[6 7]
 [2 3]]


In [31]:
print (a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1])

6
77


In [32]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print (row_r1, row_r1.shape)
print (row_r2, row_r2.shape)
print (row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [34]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [35]:
a = np.array([[1,2], [3, 4]])

# An example of integer array indexing.
# The returned array will have shape (2,) and 
print (a[[0, 1], [0, 1]])

# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1]]))

[1 4]
[1 4]


In [36]:
a = np.array([[1,2], [3, 4]])

# An example of integer array indexing.
# The returned array will have shape (2,) and 
print (a[[0, 1], [0, 1]])

# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1]]))

[1 4]
[1 4]


In [37]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print (a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print (np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [38]:
a = np.array([[1,2], [3, 4], [5, 6]])
# Find the elements of a that are bigger than 2
print (a > 2)  

# to get the actual value
print (a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [39]:
#Array math
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[7,8],[9,10],[11,12]])

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]


In [40]:
# Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [41]:
# Elementwise product; both produce the array
print (x * y)
print (np.multiply(x, y))

[[ 7 16]
 [27 40]
 [55 72]]
[[ 7 16]
 [27 40]
 [55 72]]


In [42]:
# Elementwise division; both produce the array
print (x / y)
print (np.divide(x, y))

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]


In [43]:
# Elementwise square root; produces the array
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [44]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

a = np.array([9,10])
b = np.array([11, 12])

# Inner product of vectors; both produce 219
print (a.dot(b))
print (np.dot(a, b))

219
219


In [45]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print (x.dot(a))
print (np.dot(x, a))

[29 67]
[29 67]


In [46]:
# Matrix / matrix product; both produce the rank 2 array
print (x.dot(y))
print (np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [47]:
x = np.array([[1,2],[3,4]])

# Compute sum of all elements
print (np.sum(x))
# Compute sum of each column
print (np.sum(x, axis=0))
# Compute sum of each row
print (np.sum(x, axis=1)) 

10
[4 6]
[3 7]


Transpose is one of the common operation often performed on matrix, which can be achieved using T attribute of an array object.

In [48]:
print (x)
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [49]:
v = np.array([1,2,3])
print (v)
print (v.T)

[1 2 3]
[1 2 3]


#Broadcasting


Broadcasting enables arithmetic operations to be performed between different shaped arrays. Let's look at a simple example of adding a constant vector to each row of matrix.

In [50]:
# create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create a vector
v = np.array([1, 0, 1])

# Create an empty matrix with the same shape as a
b = np.empty_like(a)   

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(3):
    b[i, :] = a[i, :] + v

print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [51]:
# Stack 3 copies of v on top of each other
vv = np.tile(v, (3, 1))  
print (vv) 

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [52]:
# Add x and vv elementwise
b = a + vv  
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [53]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])

# Add v to each row of a using broadcasting
b = a + v  
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [54]:
# Compute outer product of vectors
# v has shape (3,)
v = np.array([1,2,3])
# w has shape (2,)
w = np.array([4,5]) 
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print (np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [55]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3)

print (x + v)

[[2 4 6]
 [5 7 9]]


In [56]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column

print ((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [57]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print (x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [58]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print (x * 2)

[[ 2  4  6]
 [ 8 10 12]]
